name: gatsby-plugin-highlight
on: [push]
jobs:
  firstload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.11.0
          registry-url: https://registry.npmjs.org
      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
